etergram/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('etergrams.urls', namespace='etergrams')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etergrams/urls.py
"""defining url patterns for etergrams application"""
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #home page
    url(r'^$', views.index, name='index'),

    #page with all tags
    url(r'^tags/$', views.tags, name='tags'),

    #page with all entries for a specific tag
    url(r'^tags/(?P<tag_id>\d+)/$', views.tag, name='tag'),

    #page with all users
    url(r'^all_users/$', views.users, name='users'),

    #page with all entries for a specific user
    url(r'^user/(?P<user_id>\d+)/$', views.user, name='user'),

    #page for adding a new tag
    url(r'^new_tag/$', views.new_tag, name='new_tag'),

    #page for adding new entries
    #deprecated, dependent on a single tag, should not have created this
    #url(r'^new_entry/(?P<tag_id>\d+)/$', views.new_entry, name='new_entry'),

    #current page for adding new entries
    url(r'^new_entry/$', views.new_entry, name='new_entry'),

    #page for editing a single entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""defining url patterns for users"""
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views


urlpatterns = [
    #login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    #logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    #registration page
    url(r'^register/$', views.register, name='register'),

]

etergrams/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Tag(models.Model):
    """every available tag"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """return string representation of the model"""
        return self.text


class Entry(models.Model):
    """entry containing a photo and a description"""
    text = models.TextField()
    photo = models.ImageField(upload_to='photos', default='/photos/default.jpg')
    tag = models.ManyToManyField(Tag)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """return a shortened string representation of the model"""
        if(len(self.text) > 50):
            return self.text[:50] + "..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

etergrams/forms.py
from django import forms
from .models import Tag
from .models import Entry


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text', 'photo', 'tag']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

etergrams/views.py
from django.shortcuts import render
from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse

from .models import Tag
from .forms import TagForm
from .models import Entry
from .forms import EntryForm
from django.contrib.auth.models import User

# Create your views here.

def index(request):
    """the home page for Etergram"""
    return render(request, 'etergrams/index.html')


def tags(request):
    """show all tags"""
    tags = Tag.objects.order_by('date_added')
    context = {'tags': tags}
    return render(request, 'etergrams/tags.html', context)


def tag(request, tag_id):
    """show all entries for a single tag"""
    tag = Tag.objects.get(id=tag_id)
    entries = tag.entry_set.order_by('-date_added')
    context = {'tag': tag, 'entries': entries}
    return render(request, 'etergrams/tag.html', context)

def users(request):
    """show all users"""
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'etergrams/users.html', context)


def user(request, user_id):
    """show all entries of a specific user"""
    user1 = User.objects.get(id=user_id)
    entries = user1.entry_set.order_by('-date_added')
    for each in entries:
        tags = each.tag.all()
    context = {'user1': user1, 'entries': entries, 'tags': tags}
    return render(request, 'etergrams/user.html', context)


@login_required
def new_tag(request):
    """add a new tag"""
    if request.method != 'POST':
        form = TagForm()
    else:
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('etergrams:tags'))

    context = {'form': form}
    return render(request, 'etergrams/new_tag.html', context)

#damn, this one below took me a full day to work out; had to bite into POST requests for it to fully working
@login_required
def new_entry(request):
    """add a new entry to some tags"""
    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(request.POST, request.FILES)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.save()
            tags = request.POST.getlist('tag', '')
            for each in tags:
                new_entry.tag.add(each)
                new_entry.save()
            new_entry.save()
            return HttpResponseRedirect(reverse('etergrams:tags'))

    context = {'tag': tag, 'form': form}
    return render(request, 'etergrams/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)

    if entry.owner != request.user:
        raise Http404


    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('etergrams:tags'))

    context = {'entry': entry, 'form': form}
    return render(request, 'etergrams/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.


def logout_view(request):
    """logging the user out"""
    logout(request)
    return HttpResponseRedirect(reverse('etergrams:index'))


def register(request):
    """registering a new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('etergrams:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

etergrams/templates/etergrams/base.html
<p>
    <a href="{% url 'etergrams:index' %}">ETERGRAM</a>
    <a href="{% url 'etergrams:tags' %}">All tags</a>
    <a href="{% url 'etergrams:users' %}">All users</a>
    <a href="{% url 'etergrams:new_entry' %}">Add new entry</a>
    {% if user.is_authenticated %}
        Henlo, {{ user.username }}
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a>
        <a href="{% url 'users:login' %}">Sign in</a>
    {% endif %}
</p>

{% block content %}
{% endblock content %}

etergrams/templates/etergrams/edit_entry.html
{% extends 'etergrams/base.html' %}

{% block content %}

    <p>Edit entry: </p>

    <form action="{% url 'etergrams:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
    
{% endblock content %}

etergrams/templates/etergrams/index.html
{% extends "etergrams/base.html" %}

{%block content %}
<p>A simple copy of Instagram</p>
{%endblock content %}

etergrams/templates/etergrams/new_entry.html
{% extends 'etergrams/base.html' %}

    {% block content %}

    <p>Add a new entry: </p>

    <form action="{% url 'etergrams:new_entry' %}" method="post", enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>
    </form>



    {% endblock content %}

etergrams/templates/etergrams/new_tag.html
{% extends 'etergrams/base.html' %}

{% block content %}
<p>Add a new tag: </p>

<form action="{% url 'etergrams:new_tag' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add tag</button>
</form>


{% endblock content %}

etergrams/templates/etergrams/old.new_entry.html
{% extends "etergrams/base.html" %}

     {% block content %}

     <p><a href="{% url 'etergrams:tag' tag.id %}">{{ tag }}</a></p>

     <p>Add a new entry:</p>

    <form action="{% url 'etergrams:new_entry' tag.id %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>add entry</button>
    </form>

     {% endblock content %}

etergrams/templates/etergrams/tag.html
{% extends 'etergrams/base.html' %}

{% block content %}

<p>Tag: {{ tag }}</p>

<p>Entries:</p>


<ul>
{% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}; <a href="{% url 'etergrams:edit_entry' entry.id %}">Edit entry</a></p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>Uploaded by: <a href="{% url 'etergrams:user' entry.owner.id %}">{{ entry.owner }}</a>;
             Tags:
            {% for each in entry.tag.all %}
                <a href="{% url 'etergrams:tag' each.id %}">{{ each }}</a>
            {% endfor %}
        </p>
        <p><a href={{ entry.photo.url }}><img src="{{ entry.photo.url }}" height="20%"></a></p>
    </br>
    </li>

{% empty %}
        <li>
            There are no entries for this tag yet.
        </li>

{% endfor %}
</ul>

{% endblock content %}

etergrams/templates/etergrams/tags.html
{% extends "etergrams/base.html" %}

{%block content%}

<p>Tags</p>
<ul>
    {% for tag in tags %}
        <li>
            <a href="{% url 'etergrams:tag' tag.id %}">{{tag}}</a>
        </li>
    {% empty %}
        <li>No tags added yet</li>
    {% endfor %}
</ul>
<a href="{% url 'etergrams:new_tag' %}">Add a new tag</a>

{%endblock content%}

etergrams/templates/etergrams/user.html
{% extends "etergrams/base.html" %}


{% block content %}
<p>Owner: {{ user1 }}</p>


<p>Entries: <p>
<ul>
{% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}; <a href="{% url 'etergrams:edit_entry' entry.id %}">Edit entry</a></p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>Tags:
        {% for each in entry.tag.all %}
            <a href="{% url 'etergrams:tag' each.id %}">{{ each }}</a>
        {% endfor %}
        </p>
        <p><a href={{ entry.photo.url }}><img src="{{ entry.photo.url }}" height="20%"></a></p>
    </br>
    </li>

{% empty %}
        <li>
            This user has not posted anything yet.
        </li>
{% endfor %}
</ul>

{% endblock content %}

etergrams/templates/etergrams/users.html
{% extends "etergrams/base.html" %}

{%block content%}

<p>Users</p>
<ul>
    {% for user in users %}
        <li>
            <a href="{% url 'etergrams:user' user.id %}">{{ user }}</a>
        </li>
    {% endfor %}
</ul>
<a href="{% url 'users:register' %}">Register</a>

{%endblock content%}

users/templates/users/login.html
{% extends 'etergrams/base.html' %}

{% block content %}

{% if form.errors %}
    <p>Username and/or password don't match. Please, try again.</p>
{% endif %}

<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Log in</button>

    <input type="hidden" name="next" value="{% url 'etergrams:index' %}" />
</form>

{% endblock content %}

users/templates/users/register.html
{% extends 'etergrams/base.html' %}



{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Register</button>
        <input type="hidden" name="next" value="{% url 'etergrams:index' %}" />
    </form>


{% endblock content %}